<?php

define('ROOT_APP_PATH', __DIR__.DIRECTORY_SEPARATOR);

$env = @parse_ini_file(ROOT_APP_PATH.'.env');

if (!$env) {
    throw new Exception('Unable to parse the .env file.', 500);
}

define('DEFAULT_INPUT_CSV_FILE_PATH', ROOT_APP_PATH.'tests/input.csv');
define(
    'INPUT_CSV_FILE_PATH',
    !empty($_SERVER['REQUEST_METHOD'])
        ? DEFAULT_INPUT_CSV_FILE_PATH
        : $argv[1] ?? DEFAULT_INPUT_CSV_FILE_PATH
);

define('IS_USE_HARDCODED_RATES', empty($argv[2]));

//NON FEE SETTINGS
define(
    'AVAILABLE_NON_FEE_TRANSACTION_COUNT_PER_WEEK',
    $env['AVAILABLE_NON_FEE_TRANSACTION_COUNT_PER_WEEK']
);
define(
    'AVAILABLE_NON_FEE_TRANSACTION_SUM_PER_WEEK',
    $env['AVAILABLE_NON_FEE_TRANSACTION_SUM_PER_WEEK']
);
define(
    'AVAILABLE_NON_FEE_TRANSACTION_SUM_PER_WEEK_IN_CURRENCY',
    $env['AVAILABLE_NON_FEE_TRANSACTION_SUM_PER_WEEK_IN_CURRENCY']
);

//RATES
define('DEPOSIT_RATE', $env['DEPOSIT_RATE']);
define('WITHDRAW_PRIVATE_RATE', $env['WITHDRAW_PRIVATE_RATE']);
define('WITHDRAW_BUSINESS_RATE', $env['WITHDRAW_BUSINESS_RATE']);

define('EXCHANGERATES_API_URL', $env['EXCHANGERATES_API_URL']);
define('EXCHANGERATES_API_KEY', $env['EXCHANGERATES_API_KEY']);